//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email.Template {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Email.Template.EmailResource", typeof(EmailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;/div&gt;
        ///        &lt;div style=&quot;margin: 0px auto;max-width: 600px;padding-bottom: 50px;&quot;&gt;
        ///            &lt;h2&gt;
        ///                Abraços,&lt;br&gt;
        ///                Equipe Batalá
        ///            &lt;/h2&gt;
        ///            &lt;p Align=&quot;justify&quot;&gt;
        ///                Por favor, pedimos que você não responda esse e-mail, pois se trata de uma mensagem 
        ///                automática e não é possível dar continuidade com seu atendimento por aqui.
        ///            &lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt;div style=&quot;display: flex;margin: 0px auto;max-width: 600p [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string EmailPatternDown {
            get {
                return ResourceManager.GetString("EmailPatternDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;pt-BR&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Mensagem de E-mail&lt;/title&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@100&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;font-family: &apos;Roboto&apos;, sans-serif;
        ///  font-weight: 900;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #e5e5e5;&quot;&gt;
        ///        &lt;div style=&quot;margin: 0px auto;max-width: 600px [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string EmailPatternTop {
            get {
                return ResourceManager.GetString("EmailPatternTop", resourceCulture);
            }
        }
    }
}
