-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 09:44:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GrupoMusical
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GrupoMusical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GrupoMusical` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `GrupoMusical` ;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`ApresentacaoTipoInstrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`ApresentacaoTipoInstrumento` (
  `idApresentacao` INT NOT NULL,
  `idTipoInstrumento` INT NOT NULL,
  `quantidadePlanejada` INT NOT NULL DEFAULT 0,
  `quantidadeConfirmada` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idApresentacao`, `idTipoInstrumento`),
  CONSTRAINT `fk_ApresentacaoTipoInstrumento_Apresentacao1`
    FOREIGN KEY (`idApresentacao`)
    REFERENCES `GrupoMusical`.`Evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ApresentacaoTipoInstrumento_TipoInstrumento1`
    FOREIGN KEY (`idTipoInstrumento`)
    REFERENCES `GrupoMusical`.`TipoInstrumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ApresentacaoTipoInstrumento_TipoInstrumento1_idx` ON `GrupoMusical`.`ApresentacaoTipoInstrumento` (`idTipoInstrumento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ApresentacaoTipoInstrumento_Apresentacao1_idx` ON `GrupoMusical`.`ApresentacaoTipoInstrumento` (`idApresentacao` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Ensaio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Ensaio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGrupoMusical` INT NOT NULL,
  `tipo` ENUM('FIXO', 'EXTRA') NOT NULL DEFAULT 'FIXO',
  `dataHoraInicio` DATETIME NOT NULL,
  `dataHoraFim` DATETIME NOT NULL,
  `presencaObrigatoria` TINYINT NOT NULL DEFAULT 0,
  `local` VARCHAR(100) NULL,
  `repertorio` VARCHAR(1000) NULL,
  `idColaboradorResponsavel` INT NOT NULL,
  `idRegente` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Ensaio_Pessoa1`
    FOREIGN KEY (`idColaboradorResponsavel`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensaio_Pessoa2`
    FOREIGN KEY (`idRegente`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensaio_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_Pessoa1_idx` ON `GrupoMusical`.`Ensaio` (`idColaboradorResponsavel` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_Pessoa2_idx` ON `GrupoMusical`.`Ensaio` (`idRegente` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_GrupoMusical1_idx` ON `GrupoMusical`.`Ensaio` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`EnsaioPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`EnsaioPessoa` (
  `idPessoa` INT NOT NULL,
  `idEnsaio` INT NOT NULL,
  `presente` TINYINT NOT NULL DEFAULT 0,
  `justificativaFalta` VARCHAR(200) NULL,
  `justificativaAceita` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPessoa`, `idEnsaio`),
  CONSTRAINT `fk_PessoaEnsaio_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaEnsaio_Ensaio1`
    FOREIGN KEY (`idEnsaio`)
    REFERENCES `GrupoMusical`.`Ensaio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PessoaEnsaio_Ensaio1_idx` ON `GrupoMusical`.`EnsaioPessoa` (`idEnsaio` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_PessoaEnsaio_Pessoa1_idx` ON `GrupoMusical`.`EnsaioPessoa` (`idPessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGrupoMusical` INT NOT NULL,
  `dataHoraInicio` DATETIME NOT NULL,
  `dataHoraFim` DATETIME NOT NULL,
  `local` VARCHAR(100) NULL,
  `repertorio` VARCHAR(1000) NULL,
  `idColaboradorResponsavel` INT NOT NULL,
  `idRegente` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Ensaio_Pessoa10`
    FOREIGN KEY (`idColaboradorResponsavel`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensaio_Pessoa20`
    FOREIGN KEY (`idRegente`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensaio_GrupoMusical10`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_Pessoa1_idx` ON `GrupoMusical`.`Evento` (`idColaboradorResponsavel` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_Pessoa2_idx` ON `GrupoMusical`.`Evento` (`idRegente` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Ensaio_GrupoMusical1_idx` ON `GrupoMusical`.`Evento` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`EventoPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`EventoPessoa` (
  `idEvento` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTipoInstrumento` INT NOT NULL,
  `presente` TINYINT NOT NULL DEFAULT 0,
  `justificativaFalta` VARCHAR(200) BINARY NULL,
  `justificativaAceita` TINYINT NOT NULL DEFAULT 0,
  `status` ENUM('INSCRITO', 'DEFERIDO', 'INDEFERIDO') NOT NULL DEFAULT 'INSCRITO',
  PRIMARY KEY (`idEvento`, `idPessoa`),
  CONSTRAINT `fk_ApresentacaoPessoa_Apresentacao1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `GrupoMusical`.`Evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ApresentacaoPessoa_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ApresentacaoPessoa_TipoInstrumento1`
    FOREIGN KEY (`idTipoInstrumento`)
    REFERENCES `GrupoMusical`.`TipoInstrumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ApresentacaoPessoa_Pessoa1_idx` ON `GrupoMusical`.`EventoPessoa` (`idPessoa` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ApresentacaoPessoa_Apresentacao1_idx` ON `GrupoMusical`.`EventoPessoa` (`idEvento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ApresentacaoPessoa_TipoInstrumento1_idx` ON `GrupoMusical`.`EventoPessoa` (`idTipoInstrumento` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Figurino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Figurino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data` DATE NULL,
  `idGrupoMusical` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Figurino_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `GrupoMusical`.`Figurino` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Figurino_GrupoMusical1_idx` ON `GrupoMusical`.`Figurino` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`FigurinoApresentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`FigurinoApresentacao` (
  `idFigurino` INT NOT NULL,
  `idApresentacao` INT NOT NULL,
  PRIMARY KEY (`idFigurino`, `idApresentacao`),
  CONSTRAINT `fk_FigurinoApresentacao_Figurino1`
    FOREIGN KEY (`idFigurino`)
    REFERENCES `GrupoMusical`.`Figurino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FigurinoApresentacao_Apresentacao1`
    FOREIGN KEY (`idApresentacao`)
    REFERENCES `GrupoMusical`.`Evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoApresentacao_Apresentacao1_idx` ON `GrupoMusical`.`FigurinoApresentacao` (`idApresentacao` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoApresentacao_Figurino1_idx` ON `GrupoMusical`.`FigurinoApresentacao` (`idFigurino` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`FigurinoEnsaio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`FigurinoEnsaio` (
  `idFigurino` INT NOT NULL,
  `idEnsaio` INT NOT NULL,
  PRIMARY KEY (`idFigurino`, `idEnsaio`),
  CONSTRAINT `fk_FigurinoEnsaio_Figurino1`
    FOREIGN KEY (`idFigurino`)
    REFERENCES `GrupoMusical`.`Figurino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FigurinoEnsaio_Ensaio1`
    FOREIGN KEY (`idEnsaio`)
    REFERENCES `GrupoMusical`.`Ensaio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoEnsaio_Ensaio1_idx` ON `GrupoMusical`.`FigurinoEnsaio` (`idEnsaio` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoEnsaio_Figurino1_idx` ON `GrupoMusical`.`FigurinoEnsaio` (`idFigurino` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`FigurinoManequim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`FigurinoManequim` (
  `idFigurino` INT NOT NULL,
  `idManequim` INT NOT NULL,
  `quantidadeDisponivel` INT NOT NULL DEFAULT 0,
  `quantidadeEntregue` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idFigurino`, `idManequim`),
  CONSTRAINT `fk_FigurinoManequim_Figurino1`
    FOREIGN KEY (`idFigurino`)
    REFERENCES `GrupoMusical`.`Figurino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FigurinoManequim_Manequim1`
    FOREIGN KEY (`idManequim`)
    REFERENCES `GrupoMusical`.`Manequim` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoManequim_Manequim1_idx` ON `GrupoMusical`.`FigurinoManequim` (`idManequim` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_FigurinoManequim_Figurino1_idx` ON `GrupoMusical`.`FigurinoManequim` (`idFigurino` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`GrupoMusical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`GrupoMusical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `cep` VARCHAR(8) NULL,
  `rua` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` CHAR(2) NOT NULL DEFAULT 'SE',
  `pais` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `youtube` VARCHAR(100) NULL,
  `instagram` VARCHAR(100) NULL,
  `facebook` VARCHAR(100) NULL,
  `telefone1` VARCHAR(20) NULL,
  `telefone2` VARCHAR(20) NULL,
  `banco` VARCHAR(100) NULL,
  `agencia` VARCHAR(15) NULL,
  `numeroContaBanco` VARCHAR(15) NULL,
  `chavePIX` VARCHAR(100) NULL,
  `chavePIXTipo` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cnpj_UNIQUE` ON `GrupoMusical`.`GrupoMusical` (`cnpj` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Informativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Informativo` (
  `idGrupoMusical` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `mensagem` VARCHAR(2000) NOT NULL,
  `data` DATE NOT NULL,
  `entregarAssociadosAtivos` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idGrupoMusical`, `idPessoa`),
  CONSTRAINT `fk_GrupoMusicalPessoa_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GrupoMusicalPessoa_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_GrupoMusicalPessoa_Pessoa1_idx` ON `GrupoMusical`.`Informativo` (`idPessoa` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_GrupoMusicalPessoa_GrupoMusical1_idx` ON `GrupoMusical`.`Informativo` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`InstrumentoMusical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`InstrumentoMusical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patrimonio` VARCHAR(20) NOT NULL,
  `dataAquisicao` DATE NOT NULL,
  `status` ENUM('DISPONIVEL', 'EMPRESTADO', 'DANIFICADO') NOT NULL DEFAULT 'DISPONIVEL',
  `idTipoInstrumento` INT NOT NULL,
  `idGrupoMusical` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_InstrumentoMusical_TipoInstrumento1`
    FOREIGN KEY (`idTipoInstrumento`)
    REFERENCES `GrupoMusical`.`TipoInstrumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InstrumentoMusical_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_InstrumentoMusical_TipoInstrumento1_idx` ON `GrupoMusical`.`InstrumentoMusical` (`idTipoInstrumento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_InstrumentoMusical_GrupoMusical1_idx` ON `GrupoMusical`.`InstrumentoMusical` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Manequim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Manequim` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(2) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`MaterialEstudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`MaterialEstudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `data` DATETIME NOT NULL,
  `idGrupoMusical` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_MaterialEstudo_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MaterialEstudo_Pessoa1`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_MaterialEstudo_GrupoMusical1_idx` ON `GrupoMusical`.`MaterialEstudo` (`idGrupoMusical` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_MaterialEstudo_Pessoa1_idx` ON `GrupoMusical`.`MaterialEstudo` (`idColaborador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`MovimentacaoFigurino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`MovimentacaoFigurino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `idFigurino` INT NOT NULL,
  `idManequim` INT NOT NULL,
  `idAssociado` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `status` ENUM('DISPONIVEL', 'ENTREGUE', 'RECEBIDO', 'DANIFICADO', 'DEVOLVIDO') NOT NULL DEFAULT 'DISPONIVEL',
  `confirmacaoRecebimento` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_EntregarFigurino_Figurino1`
    FOREIGN KEY (`idFigurino`)
    REFERENCES `GrupoMusical`.`Figurino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntregarFigurino_Manequim1`
    FOREIGN KEY (`idManequim`)
    REFERENCES `GrupoMusical`.`Manequim` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntregarFigurino_Pessoa1`
    FOREIGN KEY (`idAssociado`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntregarFigurino_Pessoa2`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_EntregarFigurino_Figurino1_idx` ON `GrupoMusical`.`MovimentacaoFigurino` (`idFigurino` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_EntregarFigurino_Manequim1_idx` ON `GrupoMusical`.`MovimentacaoFigurino` (`idManequim` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_EntregarFigurino_Pessoa1_idx` ON `GrupoMusical`.`MovimentacaoFigurino` (`idAssociado` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_EntregarFigurino_Pessoa2_idx` ON `GrupoMusical`.`MovimentacaoFigurino` (`idColaborador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`MovimentacaoInstrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`MovimentacaoInstrumento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `idInstrumentoMusical` INT NOT NULL,
  `idAssociado` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `confirmacaoAssociado` TINYINT NOT NULL DEFAULT 0,
  `tipoMovimento` ENUM('EMPRESTIMO', 'DEVOLUCAO') NOT NULL DEFAULT 'EMPRESTIMO',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_DevolverInstrumento_InstrumentoMusical1`
    FOREIGN KEY (`idInstrumentoMusical`)
    REFERENCES `GrupoMusical`.`InstrumentoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DevolverInstrumento_Pessoa1`
    FOREIGN KEY (`idAssociado`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DevolverInstrumento_Pessoa2`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_DevolverInstrumento_InstrumentoMusical1_idx` ON `GrupoMusical`.`MovimentacaoInstrumento` (`idInstrumentoMusical` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_DevolverInstrumento_Pessoa1_idx` ON `GrupoMusical`.`MovimentacaoInstrumento` (`idAssociado` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_DevolverInstrumento_Pessoa2_idx` ON `GrupoMusical`.`MovimentacaoInstrumento` (`idColaborador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`PapelGrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`PapelGrupo` (
  `idPapelGrupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPapelGrupo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL DEFAULT 'F',
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` CHAR(2) NOT NULL DEFAULT 'SE',
  `dataNascimento` DATE NULL,
  `telefone1` VARCHAR(20) NOT NULL,
  `telefone2` VARCHAR(20) NULL,
  `email` VARCHAR(100) NOT NULL,
  `dataEntrada` DATE NULL,
  `dataSaida` DATE NULL,
  `motivoSaida` VARCHAR(100) NULL,
  `ativo` TINYINT NOT NULL DEFAULT 0,
  `isentoPagamento` TINYINT NOT NULL DEFAULT 0,
  `idGrupoMusical` INT NOT NULL,
  `idPapelGrupo` INT NOT NULL,
  `idManequim` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pessoa_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_PapelGrupoMusical1`
    FOREIGN KEY (`idPapelGrupo`)
    REFERENCES `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Manequim1`
    FOREIGN KEY (`idManequim`)
    REFERENCES `GrupoMusical`.`Manequim` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cpf_UNIQUE` ON `GrupoMusical`.`Pessoa` (`cpf` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_GrupoMusical1_idx` ON `GrupoMusical`.`Pessoa` (`idGrupoMusical` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_PapelGrupoMusical1_idx` ON `GrupoMusical`.`Pessoa` (`idPapelGrupo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_Manequim1_idx` ON `GrupoMusical`.`Pessoa` (`idManequim` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`PessoaTipoInstrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`PessoaTipoInstrumento` (
  `idPessoa` INT NOT NULL,
  `idTipoInstrumento` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `idTipoInstrumento`),
  CONSTRAINT `fk_Pessoa_has_TipoInstrumento_Pessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_TipoInstrumento_TipoInstrumento1`
    FOREIGN KEY (`idTipoInstrumento`)
    REFERENCES `GrupoMusical`.`TipoInstrumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_has_TipoInstrumento_TipoInstrumento1_idx` ON `GrupoMusical`.`PessoaTipoInstrumento` (`idTipoInstrumento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Pessoa_has_TipoInstrumento_Pessoa_idx` ON `GrupoMusical`.`PessoaTipoInstrumento` (`idPessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`ReceitaFinanceira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`ReceitaFinanceira` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `idGrupoMusical` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ReceitaFinanceira_GrupoMusical1`
    FOREIGN KEY (`idGrupoMusical`)
    REFERENCES `GrupoMusical`.`GrupoMusical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ReceitaFinanceira_GrupoMusical1_idx` ON `GrupoMusical`.`ReceitaFinanceira` (`idGrupoMusical` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`ReceitaFinanceiraPessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`ReceitaFinanceiraPessoa` (
  `idReceitaFinanceira` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valorPago` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `dataPagamento` DATETIME NOT NULL,
  `observacoes` VARCHAR(200) NULL,
  `status` ENUM('ABERTO', 'ENVIADO', 'PAGO', 'ISENTO') NOT NULL DEFAULT 'ABERTO',
  PRIMARY KEY (`idReceitaFinanceira`, `idPessoa`),
  CONSTRAINT `fk_ReceitaFinanceiraPessoa_ReceitaFinanceira1`
    FOREIGN KEY (`idReceitaFinanceira`)
    REFERENCES `GrupoMusical`.`ReceitaFinanceira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReceitaFinanceiraPessoa_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `GrupoMusical`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ReceitaFinanceiraPessoa_Pessoa1_idx` ON `GrupoMusical`.`ReceitaFinanceiraPessoa` (`idPessoa` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ReceitaFinanceiraPessoa_ReceitaFinanceira1_idx` ON `GrupoMusical`.`ReceitaFinanceiraPessoa` (`idReceitaFinanceira` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GrupoMusical`.`TipoInstrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoMusical`.`TipoInstrumento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `GrupoMusical`.`Manequim`
-- -----------------------------------------------------
START TRANSACTION;
USE `GrupoMusical`;
INSERT INTO `GrupoMusical`.`Manequim` (`id`, `tamanho`, `descricao`) VALUES (1, 'P', 'PEQUENO');
INSERT INTO `GrupoMusical`.`Manequim` (`id`, `tamanho`, `descricao`) VALUES (2, 'M', 'MÉDIO');
INSERT INTO `GrupoMusical`.`Manequim` (`id`, `tamanho`, `descricao`) VALUES (3, 'G', 'GRANDE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `GrupoMusical`.`PapelGrupo`
-- -----------------------------------------------------
START TRANSACTION;
USE `GrupoMusical`;
INSERT INTO `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`, `nome`) VALUES (1, 'ASSOCIADO');
INSERT INTO `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`, `nome`) VALUES (2, 'COLABORADOR');
INSERT INTO `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`, `nome`) VALUES (3, 'ADMINISTRADOR GRUPO');
INSERT INTO `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`, `nome`) VALUES (4, 'ADMINISTRADOR SISTEMA');
INSERT INTO `GrupoMusical`.`PapelGrupo` (`idPapelGrupo`, `nome`) VALUES (5, 'REGENTE');

COMMIT;

